# Parameter grid for hyperparameter search
# Note: For classifiers, we use strings; later we map these to actual classes.
param_grid:
  # - clf: "LogisticRegression"
  #   features__recordings_parsel: [[], ["a"], ["poem"]]
  #   features__recordings_wav2vec2: [[], ["a"], ["poem"], ["a", "poem"]]
  #   features__wav2vec2_layer: [0, 4, 8]
  #   features__wav2vec2_embedding_statistics: ["mean_std", "mean"]
  #   select__k: [10, 20, 30]
  #   wav2vec2_pca__n_components: [5, 10, 15]
  #   clf__C: [0.1, 1.0]
  # - clf: "XGBClassifier"
  #   features__recordings_parsel: [[], ["a"], ["poem"]]
  #   features__recordings_wav2vec2: [[], ["a"], ["poem"], ["a", "poem"]]
  #   features__wav2vec2_layer: [0, 4, 8]
  #   features__wav2vec2_embedding_statistics: ["mean_std", "mean"]
  #   select__k: [10, 20, 30]
  #   wav2vec2_pca__n_components: [5, 10, 15]
  #   clf__n_estimators: [25, 50, 100]
  #   clf__max_depth: [5, 10]
  #   clf__learning_rate: [0.1, 0.01]
  #   clf__colsample_bytree: [0.5, 0.8]
  - clf: "RandomForestClassifier"
    features__recordings_parsel: [[], ["a"]]
    features__recordings_wav2vec2: [["a"], ["poem"]]
    features__wav2vec2_layer: [4]
    features__wav2vec2_embedding_statistics: ["mean"]
    select__k: [20, 30]
    wav2vec2_pca__n_components: [15, 25]
    clf__n_estimators: [50, 100]
    clf__max_depth: [5, 10]
    clf__max_features: ["sqrt"]
    clf__min_samples_leaf: [2]
  - clf: "SVC"
    features__recordings_parsel: [[], ["a"]]
    features__recordings_wav2vec2: [["a"], ["poem"]]
    features__wav2vec2_layer: [4]
    features__wav2vec2_embedding_statistics: ["mean"]
    select__k: [20, 30]
    wav2vec2_pca__n_components: [15, 25]
    clf__C: [0.1, 1.0]
    clf__gamma: ["scale"]
    clf__kernel: ["linear", "rbf"]